# Generated by Django 5.2.7 on 2025-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recurringexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringexpense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='recurrence_type',
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='recurrence',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
