# Generated by Django 5.2.7 on 2025-11-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_recurringexpense_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='amount_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='recurrence',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
