# Generated by Django 5.2.7 on 2025-11-22 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_paymentstatus_amount_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='group_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.groupexpense'),
        ),
    ]
