# Generated by Django 5.2.7 on 2025-11-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_expense_group_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='marked_by_creator',
            field=models.BooleanField(default=False),
        ),
    ]
